version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../fastapi.dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./model_cache:/app/model_cache
      - ./backend/services/wav2vec_transcription.json:/app/services/wav2vec_transcription.json
    environment:
      - PYTHONUNBUFFERED=1
      - TRANSFORMERS_CACHE=/app/model_cache
      - HF_HOME=/app/model_cache
    networks:
      - default
    
  frontend:
    build:
      context: ./frontend
      dockerfile: ../react.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    depends_on:
      - backend
    networks:
      - default

  llmteacher:
    build:
      context: ./LLMTeacher
      dockerfile: ../llmteacher.dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./LLMTeacher:/app
      - ./LLMTeacher/app/data:/app/app/data
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - default
    depends_on:
      - backend

networks:
  default:
    driver: bridge